"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""


def fib_gen(lmt):  # Function that generates a Fibonacci Series to the limit value.
    a = 0
    b = 1
    while b <= lmt:
        yield (a + b)
        a, b = b, (a + b)


print(sum(i for i in fib_gen(4000000) if i % 2 == 0))
